### ISSUE TITLE
Errors in test

### ISSUE THREAD

**Issue by Erofili-K** [GervinFung/SimpleParallelChessAI#5]
Hello, I was looking the code and i saws that in the test folder, there is an error in every calss due to an import you put.

**Comment by Erofili-K** [comment]
> Hello, I was looking the code and i saws that in the test folder, there is an error in every calss due to an import you put.

I have a solution for this issue , and if you give me permission i can upload a new version without the error. Thank you

**Comment by GervinFung** [comment]
> > Hello, I was looking the code and i saws that in the test folder, there is an error in every calss due to an import you put.
> 
> I have a solution for this issue , and if you give me permission i can upload a new version without the error. Thank you

Hi, sorry for the late reply bcoz I missed your issue, you can create a pull request if you want to
